### ISSUE TITLE
Docs do not show `ceramic` as an arg to `IDWConfig`

### ISSUE THREAD

**Issue by Schwartz10** [ceramicstudio/js-3id-did-provider#102]
The documentation in the repo shows 3 arguments passed to the `ThreeIdProvider` - `getPermission`, `authID`, `authSecret`, but it does not show `ceramic` which is a required config argument. This will likely cause confusion

**Comment by oed** [comment]
Fixed

**Comment by oed** [comment]
Err, only partially.

**Comment by oed** [comment]
Should be updated now.
