### ISSUE TITLE
Different 3ID generated after nuking ceramic environment

### ISSUE THREAD

**Issue by Schwartz10** [ceramicstudio/js-3id-did-provider#116]
1. Spin up ceramic daemon
2. create new 3ID, get a did
3. spin down ceramic
4. delete the entire pin store (nuke environment)
5. spin up ceramic
6. create new 3id, get a did

The did in step 2 and step 6 do not match, even when using the same seed. 

I'm not entirely sure if this is expected or not, but it seems problematic - what if I want to change the ceramic node I'm connected to?

**Comment by stbrody** [comment]
Someone who's worked more on 3id-did-provider may know more here, but from reading the code it looks like whenever we create a 3id we use the `deterministic` flag (see [here](https://github.com/ceramicstudio/js-3id-did-provider/blob/961cc2c7b29d7e44903f664633f2e8a68b1d0b0c/src/keychain.ts#L230) and [here](https://github.com/ceramicstudio/js-3id-did-provider/blob/961cc2c7b29d7e44903f664633f2e8a68b1d0b0c/src/keyring.ts#L213)), so then yes that does sound like surprising behavior.  With the same seed, using the `deterministic` option to create the 3id DID document, I would expect you to get the same ceramic DocID and thus the same 3ID DID.

@oed @PaulLeCam

**Comment by oed** [comment]
> The did in step 2 and step 6 do not match, even when using the same seed.

Can you please provide the code you use for these steps? If you are using `authSecret` then this is expected, if you are using `seed` then this is a bug.

**Comment by Schwartz10** [comment]
Iiiiinteresting. Would you mind (if possible) briefly explaining why this is the case? Using `authSecret` I reckon is like adding the first authMethod, so the seed gets randomly generated, whereas using the seed directly just creates the DID straight up?

If that intuition is right... does that mean that using a seed is faster than using an authSecret for the first time creating a 3ID?

**Comment by oed** [comment]
> Would you mind (if possible) briefly explaining why this is the case? 

Because if you have multiple auth methods (`authSecret` + `authId`)  it doesn't really make sense for one of these to get a special treatment to be used as a seed.

> Using authSecret I reckon is like adding the first authMethod, so the seed gets randomly generated, whereas using the seed directly just creates the DID straight up?
> If that intuition is right... does that mean that using a seed is faster than using an authSecret for the first time creating a 3ID?

Yep, you are correct about both of these things :)
