### ISSUE TITLE
Can't resolve 'multicodec/src/base-table.json'

### ISSUE THREAD

**Issue by RobertoSnap** [ceramicstudio/js-3id-did-provider#119]
**Describe the bug**
In a React application, running with Yarn (react-scripts start). I get this error message: 

```Module not found: Can't resolve 'multicodec/src/base-table.json' in SOME_FOLDER ```

Tried with version 0.4.0, 0.5.0 and 0.5.1,all give this error. I'm using the same versions in another Node project, where it does not give this error message.

Saw some cases in Discord: https://discord.com/channels/682786569857662976/682789574249807918/822200993122877451

It resolved by following this:
https://discord.com/channels/682786569857662976/682789574249807918/822250993932173322
yarn add multicodec@^0.5.4

Just adding an issue here to keep track. If not necessary, tell me and I will close it :) 

**To Reproduce**
Not applicable

**Expected behavior**
Don't have to install additional packages.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version 89

**Comment by oed** [comment]
Thanks! This issue can be resolved by updating to the latest js-ceramic releases in this package.

**Comment by oed** [comment]
This should be fixed by now. Please reopen if not.
