### ISSUE TITLE
Signatures made with unanchored keys can become retroactively invalid after a key rotation

### ISSUE THREAD

**Issue by stbrody** [ceramicstudio/js-3id-did-provider#138]
Imagine a 3id is created with a certain signing key `K0`.  The genesis commit for the 3id has not yet been anchored, but the signing key is used to sign many messages, including some Ceramic commits on other streams, on behalf of the 3id DID.  Now that key is revoked and a new signing key is added in its place, `K1`.  Since `K0` was never anchored, it never had a timestamp associated with when it was valid.  Now that it has been revoked, any signature validation of any signatures made by `K0` will get rejected as invalid since the key has been revoked, even if they were made when the key was in fact valid, because we don't have the timestamp information to prove when it was valid.  This situation is now unrecoverable - new anchors performed for the 3id stream will give a timestamp to when `K1` became valid, but will not help us verify signatures from `K0`.

What can we do about this?  The best option I can think of is to not allow 3ids to create signatures using keys that haven't yet been anchored.  This prevents users from creating signatures that might later on become invalid in a way that can't be recovered from.  This does, however, create a UX issue where newly added keys won't be immediately usable until the stream becomes anchored, which may take a while.  That problem, however, will get better over time as there are more anchor services available on the network which provide faster anchor windows, and eventually when we have the validator network the problem will go away almost entirely as anchors will happen very fast.  The problem of the signatures that can't be validated after a key rotation due to a missing anchor, however, will never get better and can cause major user pain as previously valid streams become suddenly invalid when a key is rotated within the controller's 3id.

**Comment by stbrody** [comment]
@oed, this is something @ukstv talked about earlier today.  We have already seen this happen with one of our partners.

Also, I don't seem to have the permissions to set labels or change the zenhub pipeline for tickets in this repo, so @oed please triage this appropriately so it doesn't get lost.

**Comment by oed** [comment]
Is this a theoretical issue or have we actually seen it somewhere? 

Imo `K0` aka genesis should be valid until the first anchor we observe in the stream. 
>  The best option I can think of is to not allow 3ids to create signatures using keys that haven't yet been anchored.

Currently when you rotate to a new key the 3id-did-provider will keep signing with the old key until the new key has been anchored.

I think a better option here should be that we only allow key rotations iif the previous rotation has been anchored.

**Comment by stbrody** [comment]
> Is this a theoretical issue or have we actually seen it somewhere?
We have actually seen this happen with one of our partners.

> I think a better option here should be that we only allow key rotations iif the previous rotation has been anchored.

This is a much better idea than what I said.  We should do this!

**Comment by oed** [comment]
> We have actually seen this happen with one of our partners.

Ok, interesting. Would be good to see the stream that actually broke to learn what happened exactly!

**Comment by stbrody** [comment]
@ukstv should have the streamId

**Comment by stbrody** [comment]
From @ukstv on discord:

So, here is all I know about the mis-anchored-thus-invalid DID.

By design 3id consists of few docs. Two are of interest here. One is actual 3id stream, which is a tile, that contains public keys. Another is keychain. It contains actual keys. The keychain stream is controlled by 3id, which means the verification of the stream depends on the state of 3id.

Here is what happened with the partner that hit this issue. A person created a 3id. Then the person rotated the keys. Technically, it means updating 3id and the keychain streams. Both have to be anchored. For happy path, both are anchored, and the user happily continues to sign streams with an updated 3id. The partner found unhappy path. 3id stream was anchored, while anchor for the keychain failed. The latest commit for the keychain is authored by, say, 3id v0. When we try to re-create the state by applying all the commits, now, we see 3id being v1 since anchor time, and keychain commit still signed by 3id v0. Without anchor commit for the keychain, we have no information to determine when the commit happened. Now we have 3id v1, and consider 3id v0 as being revoked. With our heuristic for treating the non-timestamped commit as being signed now, the signature for the last keychain commit becomes invalid.

For reference: link to the anchor request that contains stream id, commit cid: https://cas-clay.3boxlabs.com/api/v0/requests/bagcqcerah4n5xtc6rj3rquwsgoyqscguf7nlhrk3rmtrd6loti2ujectvxaq

I see few ways to go about it. (1) It's an extremely rare case, so we just go on without doing anything. (2) We somehow make multiple anchors simultaneous/atomic.

The latter can be either re-architecting 3id stream design so that all of the current streams are merged into one. Or we anchor keychain then anchor 3id stream. Or maybe there is something else, to make sure 3id can not be invalidated by one of the sub-streams failed anchor.

**Comment by stbrody** [comment]
FWIW, I'm not convinced this is an **extremely** rare case.  Failed anchors can and will happen, and having one failed anchor be capable of completely invalidating a 3id is a pretty terrible failure mode

**Comment by stbrody** [comment]
Can we still do @oed's idea of not allowing a key rotation if the previous one isn't anchored, but expand it to check that not just the 3id stream is anchored but also the keychain stream?

**Comment by oed** [comment]
> Can we still do @oed's idea of not allowing a key rotation if the previous one isn't anchored, but expand it to check that not just the 3id stream is anchored but also the keychain stream?

No that wouldn't help.

**Comment by stbrody** [comment]
I believe at one point we said this could be resolved by not allowing any signatures to be performed by 3ids unless both the 3id and keychain stream are anchored.  We rejected that approach because it could mean your DID becomes unusable for up to 12 hours whenever you do a key rotation, given how infrequently we currently anchor on mainnet.

I'm starting to think that this might still be the best bet for fixing this.  It's probably the easiest mitigation to build technically, and it would actually create incentives for others to run anchor services with shorter anchor intervals.  If we wanted, we could even run a separate anchor service just for our future 3id management app which anchored more frequently.

**Comment by oed** [comment]
> I'm starting to think that this might still be the best bet for fixing this.

This would totally wreak UX. 3ID Connect will also always use 3Box Labs Ceramic and CAS node.

**Comment by oed** [comment]
No that would be a potential security risk.

**Comment by oed** [comment]
An approach for how to fix this issue can be found here: https://threebox.notion.site/Failed-anchor-in-key-rotation-invalidates-3id-fec7b82a5b994213b9cfb731569b13f8
