### ISSUE TITLE
space.syncDone hangs

### ISSUE THREAD

**Issue by balasan** [ceramicstudio/js-3id-did-provider#34]
**Describe the bug**
space.syncDone when using identity-wallet provider with 3box-js

**To Reproduce**
```
        const provider = idWallet.get3idProvider();
        const box = await Box.openBox(null, provider);
        await box.syncDone; 
        const space = await box.openSpace('relevant');
        await space.syncDone; // <---- this hangs, no reject, no resolve
```

**Expected behavior**
Resolved promise

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 80

**Additional context**
3box version: 1.17.0
identity-wallet version: 1.1.1

**Comment by oed** [comment]
Closing as this package no longer can be used with 3box-js
