### ISSUE TITLE
IDWallet.create => error: digest should be a Uint8Array

### ISSUE THREAD

**Issue by Schwartz10** [ceramicstudio/js-3id-did-provider#92]
**Describe the bug**
When I try to create a new identity-wallet instance, I get:

`digest should be a Uint8Array` error, thrown from the multihashes library 

```
    digest should be a Uint8Array

      at Object.encode (node_modules/multihashes/src/index.js:135:11)
      at Multihashing (node_modules/multihashing-async/src/index.js:17:20)
      at Object.<anonymous>.exports.cid (node_modules/ipld-dag-cbor/src/util.js:180:21)
```

I'm running node v14.9.0 and:

```
    "identity-wallet": "^2.0.0-alpha.18",
    "dids": "^0.7.0",
    "@ceramicnetwork/ceramic-cli": "^0.13.0",
    "@ceramicnetwork/ceramic-http-client": "^0.7.1",
    "@ceramicstudio/idx": "^0.3.0",
    "@ceramicstudio/idx-schemas": "^0.1.5",
    "@ceramicstudio/idx-tools": "^0.3.1",
```

I've tried with several authId's and authSecrets as well as raw seed, all of them report this error when creating an identity wallet.

**Comment by Schwartz10** [comment]
So here's what happens:
1. I call identitywallet.create https://github.com/3box/identity-wallet-js/blob/develop/src/identity-wallet.ts#L61
2. When creating a new keychain, keychain.load gets called https://github.com/3box/identity-wallet-js/blob/develop/src/identity-wallet.ts#L86
3. inside Keychain.load, Keychain.create gets called https://github.com/3box/identity-wallet-js/blob/develop/src/keychain.ts#L203
4. Inside Keychain.create, await threeIdx.create3idDoc https://github.com/3box/identity-wallet-js/blob/develop/src/keychain.ts#L216 gets called

The id wallet tests pass for me locally, so this _seems_ like it might be a ceramic-http-client issue

**Comment by Schwartz10** [comment]
Related rabbit hole I went down: https://github.com/multiformats/js-multihashing-async/issues/84

**Comment by oed** [comment]
Closing.

> The fix is to use https://www.npmjs.com/package/jest-environment-uint8array as the jest test environment.
